# Python for Chemical Reaction Engineering Part 3 - Data structure essentials

Data can be manipulated in different formats. There are many ways to do this, and they can be a bit tricky to handle

## Basic data types

The three basic types of data:
- **Scalars** are single values
- **Strings** are single sets of letters
- **Data structures** are sets of scalars and strings

### Scalars

This is a single value and can full under a few different *types*:

- **int** refers to an integer. **Examples:** 1, 42, 1571
- **float** is a floating doint decimal approximation of a value. This is often what we work with. **Examples:** 1.0, 3.14159,20.11111
- **complex** refers to complex numbers that have an imaginary part. **Examples:** 4.2 + 6i. *Note: Python displays a 'j' instead of an 'i'*

### Strings

**str** refers to a 'string' of characters. These are declared in Python with single, double, or triple quotes. Often it will not matter which convention you use, but there are specific exceptions. Technically a string is not a 'scalar,' but for simplicity  **Examples:** 'A',"Penguin",''''Kevin the Penguin'''

Another data type that is sort of an integer and sort of a string is a Boolean or **bool**. This is a binary entity which can either be 'True' or 'False.' In Python we can also not that True=1 and False=0 or [].

### Data structures

Oftentimes we will work with collections of scalars or strings, but usually just scalars. There are ***many*** ways to organize and manipulate data, all with major or subtle pros and cons. We will only use a few:

- **Lists** are the default data structure. They are built into the basic programming of Python. A list is **indexed**, meaning that each element has an assigned index value, **ordered** meaning that the precise order of these indices is important, and **mutable**, meaning that the contents can be changed after creation. These can contain scalars or strings or both. It is also possible to add or remove entries with certain commands.
- **Tuples** are like lists, but they are **immutable** meaning they can not be altered after creation-they can only be overwritten
- **Dictionaries** are like lists but are **not ordered** and inlcude **keys** that can be used to access complex data with words rather than indices. A simple usage could be to create an atomic masses dictionary. Accessing the 'rhenium' entry could return 186.207.
- **Numpy arrays** are mathematical arrays like those used by default in MATLAB and are **what we do most of our math with.** These are very similar to lists but are better suited for mathematical operations. They can have **multiple dimensions** and therefore also represent matrices. To use a numpy array, you have to first import the numpy package.
- **Pandas dataframes** are sort of a hybrid between dictionaries and numpy arrays. They allow for easy, fast math with large sets of indexed data, and the data can be easily manipulated. We might create, for example, a dataframe containing columns of reaction times, conversions, concentrations, and selectivities. We can use these to quickly find the selectivity of a specific species at a specific time or even the selectivity of a species at a certain conversion.


## Working with data

### Defining and displaying values

When a variable is first defined, the convention is simple-write the variable name, an equals sign, and then the value. To set x equal to 4 type:

    x = 4
    
If you then end a code block with simply the name of the variable, it will print by default. If it is not the last line and you want to print the output, you can do so with the 'print' command:

    print(x)
    
You can add a line break with '\n'. Doing this more than once will add more than one line. By default, adding a new 'print' command will move you to the next line, so adding '\n' to the beginning adds a blank row between the previous statment and the current one:

    print('\n',x,'\n\n\n',x)
    
You can combine this with text like so:

    print('\n The value of x is',x)
    
To control the number of decimals, you can write it like this:
    
    print('\n The value of x with 4 decimals is','{:.4f}'.format(x))
    
This reported the value as a float (thus the f) with 4 decimal points.

We can now either redefine this variable or generate new ones from it.

    x = 42
    y = 2*x+1
    print('\n x is now',x,'and y is now',y)

We define strings using quotations. When we add them together we get a new string where everything is stuck together:

    string_1 = 'Chemical'
    string_2 = 'Engineering'
    string_3 = string_1 + string_2
    print('\n',string_1,'+',string_2,'=',string_3)
    
Note that a space was not automatically created. We would need to add a ' ' string in between to do so.

In [169]:
x=4

print(x)

print('\n',x,'\n\n\n',x)

print('\n The value of x is',x)

print('\n The value of x with 4 decimals is','{:.4f}'.format(x))

x = 42
y = 2*x+1
print('\n x is now',x,'and y is now',y)

string_1 = 'Chemical'
string_2 = 'Engineering'
string_3 = string_1 + string_2
print('\n',string_1,'+',string_2,'=',string_3)

4

 4 


 4

 The value of x is 4

 The value of x with 4 decimals is 4.0000

 x is now 42 and y is now 85

 Chemical + Engineering = ChemicalEngineering


### Working with lists and tuples

First we will talk about creating these. We will make one version of each that just has [10,20,30,40].

    x_list = [10,20,30,40]
    x_tuple = (10,20,30,40)

Notice that a list uses square brackets and a tuple uses round brackets.

We can determine the type of any data using the "type" command:

    print('\n x is a,'type(x))
    print('\n x_list is a,'type(x_list))
    print('\n x_tuple is a,'type(x_tuple))
    
Now it is important to understand **indexing**. The **Python convention is to start with index 0 rather than 1**, in constrast to some other languages such as MATLAB. To find the first element of each, use square brackets to select element 0:

    print('\n The first element of x_list is',x_list[0])
    print('\n The second element of x_tuple is',x_tuple[1])
    
The value of an element can be reassigned in a list but not in a tuple. For example, the third element (index 2) of the list can be changed to 100 as follows:
    
    x_list[2] = 100
    print('\n Now x_list is',x_list)
    
The same command for the tuple will not work.

To add an element to a list, you can use **append**. Python sometimes uses **dot notation** to access **methods** like this. For example, we can add a fifth element equal to 45 to the list as follows:

    x_list.append(45)
    print('\n Now x_list is',x_list)
    
You can also insert elements. For example, we can insert a '4' in the third element (index=2):

    x_list.insert(2,4)
    print('\n Now x_list is',x_list)

If you add two lists together, it just stacks them on top of each other. For example, adding list_1=[1,2,3] to list_2=[,40,50,60] could give either [1,2,3,40,50,60] or [40,50,60,1,2,3] depending on the order:

    list_1 = [1,2,3]
    list_2 = [40,50,60]
    print('\n list_1 + list2 =',list_1+list_2)
    print('\n list_2 + list1 =',list_2+list_1)

Notice that no math was done in any of this. We could have used strings instead. For example:

    list_strings_1 = ['ethanol','1-butanol','1-hexanol']
    list_strings_2 = ['1-octanol','1-decanol']
    print('\n list_strings_1 =',list_strings_1)
    print('\n list_strings_2 =',list_strings_2)
    print('\n list_strings_1 + list_strings_2=',list_strings_1+list_strings_2)
    
The length of an array can be determined with the **len()** function:

    print('\n The length of x_list is',len(x_list))

In [170]:
x = 42
x_list = [10,20,30,40]
x_tuple = (10,20,30,40)

print('\n x is a',type(x))
print('\n x_list is a',type(x_list))
print('\n x_tuple is a',type(x_tuple))

print('\n The first element of x_list is',x_list[0])
print('\n The second element of x_tuple is',x_tuple[1])

x_list[2] = 100
print('\n Now x_list is',x_list)

x_list.append(45)
print('\n Now x_list is',x_list)

x_list.insert(2,4)
print('\n Now x_list is',x_list)

list_1 = [1,2,3]
list_2 = [40,50,60]
print('\n list_1 + list2 =',list_1+list_2)
print('\n list_2 + list1 =',list_2+list_1)

list_strings_1 = ['ethanol','1-butanol','1-hexanol']
list_strings_2 = ['1-octanol','1-decanol']
print('\n list_strings_1 =',list_strings_1)
print('\n list_strings_2 =',list_strings_2)
print('\n list_strings_1 + list_strings_2 =',list_strings_1+list_strings_2)

print('\n The length of x_list is',len(x_list))


 x is a <class 'int'>

 x_list is a <class 'list'>

 x_tuple is a <class 'tuple'>

 The first element of x_list is 10

 The second element of x_tuple is 20

 Now x_list is [10, 20, 100, 40]

 Now x_list is [10, 20, 100, 40, 45]

 Now x_list is [10, 20, 4, 100, 40, 45]

 list_1 + list2 = [1, 2, 3, 40, 50, 60]

 list_2 + list1 = [40, 50, 60, 1, 2, 3]

 list_strings_1 = ['ethanol', '1-butanol', '1-hexanol']

 list_strings_2 = ['1-octanol', '1-decanol']

 list_strings_1 + list_strings_2 = ['ethanol', '1-butanol', '1-hexanol', '1-octanol', '1-decanol']

 The length of x_list is 6


### Working with numpy arrays

Many Python-based numerical evaluations involve numpy arrays. To use them, you first have to import numpy. It is conventional to import it 'as np' so that you can write 'np' instead of 'numpy' when you want to use it. This is done as follows:

    import numpy as np
    
Once imported, you can define a numpy array from a list. Two ways of getting to the same numpy array containing [10,20,30,40] are as follows:

    x_list = [10,20,30,40]
    array_1 = np.array(x_list)
    array_2 = np.array([10,20,30,40])
    print('\n Method 1 gives:',array_1)
    print('\n Method 2 gives:',array_2)
    
It is important to note, however, that these are *neither* row *nor* column vectors as written. These are purely "one-dimensional" and are not technically 1x4 arrays but rather 0x4 arrays. This can cause problems when doing math. To specify an array as a **row vector**, add another set of brackets:

    array_1_row = np.array([[10,20,30,40]])
    print('\n A 1D row vector of the array is:\n', array_1_row)

A **column vector** is most easily created by making the **tranpose** of a row vector using the **.T** method:

    array_1_column = np.array([[10,20,30,40]]).T
    print('\n A 1D column vector of array is:\n', array_1_column)
    
Numpy elements can be changed in the same way as lists:

    array_1[0] = 26
    print('\n array_1 is now',array_1)
    
**All elements can be mutiplied by a single value easily:**

    print('\n 2*array_1 =',2*array_1)
    
**Element-wise addition** can be done with a simple '+':

    array_3 = np.array([1,2,3,4])
    array_4 = array_1+array_3
    print('\n',array_1,'+',array_3,'=',array_4)
    
Element-wise subtraction is the same.

**Element-wise multiplication** can be done with a simple '*':

    array_5 = array_1*array_3
    print('\n',array_1,'*',array_3,'=',array_5)

A **matrix dot product** uses the **np.dot** function:

    array_6 = np.dot(array_1,array_1)
    print('\n',array_1,'dot',array_1,'=',array_6)
    
A matrix can be created either with **np.matrix()** or simply with **np.array()** but with two dimensions:

    numpy_version = np.array(([1,2,3],[4,5,6]))
    print('\n 2D matrix:\n',matrix_version)
    print('\n 2D array:\n',numpy_version)

Usually an array is better to work with. The main difference is what happens with default operations, such as multiplication. With numpy arrays, multiplication is element-wide. With matrices, it is the dot product.

The **number of dimensions** in an array can be found with **.dim**:

    print('\n array_1 has',array_1.ndim,'dimensions')
    print('\n numpy_version has',numpy_version.dim,'dimensions')

The **number of elements** can be read from **.size**:

    print('\n array_1 has',array_1.size,'elements')
    print('\n numpy_version has',numpy_version.size,'elements')

The size of an array can be addressed with **np.shape()**. This is where the difference between a default 1D numpy array, row vector, and column vector will differ

    print('\n The shape of array_1 is',np.shape(array_1))
    print('\n The shape of numpy_version is',np.shape(numpy_version))
    
Note that the shape of the 1-D array is (5,) not (5,1) or (1,5). When a numpy array is made, it is **by default neither a row nor column vector**. **To turn a 1-D array into a row or column vecor**, the simplest method is to simply add an axis:

    array_1_row = array_1[np.newaxis,:]
    array_1_column = array_1[:,np.newaxis]
    print('\n array_1_row is',array_1_row,'with shape',np.shape(array_1_row))
    print('\n array_1_column is',array_1_column,'with shape',np.shape(array_1_column))

Some **very convenient arrays** that can be generated include **arrays of all ones with np.ones(dim)**, **arrays of all zeros with np.zeros(dim)**, and **arrays with evenly spaced values with np.linspace(val1,val2,num=#elements):

    print('\n',np.ones(3,4))
    print('\n',np.zeros(3,4)
    print('\n',np.linspace(1,5,num = 11)
    
Appending is a bit different with numpy arrays. To add another element, you need to redefine your array using np.append(). For example, a fifth element of '6' can be added to array_1 as follows:

    array_1 = np.append(array_1,6)
    print('\n array_1 is now',array_1)
    
Multiple arrays can be combined with **np.concatenate()**:

    print('\n Concatenating',array_1,'with',array_2,'gives',np.concatenate((array_1,array_2)))
    
Notice the double parentheses; this is important. You are putting in one element consisting of two arrays, not two elements that are each arrays. **This is an easy mistake to make**.

Multiple **rows** of the **same size** can be **stacked** with **np.hstack** and the same is true with **columns** and **vstack**:

    print('\n',array_1_row,'on',2*array_1_row,'makes',np.hstack(array_1_row,2*array_1_row))

Some final things to cover include **simple math on arrays** and **statistics**. You can add all elements together with **.sum()**, find the max value with **.max()**, find the min value with **.max()**, find the mean with **.mean()**.
    
    print('\n array_1.sum() =',array_1.sum())
    print('\n array_1.max() =',array_1.max())
    print('\n array_1.min() =',array_1.min())
    print('\n array_1.mean() =',array_1.mean())


In [3]:
import numpy as np

x_list = [10,20,30,40]
array_1 = np.array(x_list)
array_2 = np.array([10,20,30,40])
print('\n Method 1 gives:',array_1)
print('\n Method 2 gives:',array_2)

array_1_row = np.array([[10,20,30,40]])
print('\n A 1D row vector of the array is:\n', array_1_row)

array_1_column = np.array([[10,20,30,40]]).T
print('\n A 1D column vector of array is:\n', array_1_column)

array_1[0] = 26
print('\n array_1 is now',array_1)

print('\n 2*array_1 =',2*array_1)

array_3 = np.array([1,2,3,4])
array_4 = array_1+array_3
print('\n',array_1,'+',array_3,'=',array_4)

array_5 = array_1*array_3
print('\n',array_1,'*',array_3,'=',array_5)

array_6 = np.dot(array_1,array_1)
print('\n',array_1,'dot',array_1,'=',array_6)

matrix_version = np.matrix(([1,2,3],[4,5,6]))
numpy_version = np.array(([1,2,3],[4,5,6]))
print('\n 2D matrix:\n',matrix_version)
print('\n 2D array:\n',numpy_version)

print('\n array_1 has',array_1.ndim,'dimensions')
print('\n numpy_version has',numpy_version.ndim,'dimensions')

print('\n array_1 has',array_1.size,'elements')
print('\n numpy_version has',numpy_version.size,'elements')

print('\n The shape of array_1 is',np.shape(array_1))
print('\n The shape of array_1_row is',np.shape(array_1_row))
print('\n The shape of array_1_column is',np.shape(array_1_column))
print('\n The shape of numpy_version is',np.shape(numpy_version))

array_1 = np.append(array_1,6)
print('\n array_1 is now',array_1)

print('\n',np.ones([3,4]))
print('\n',np.zeros([3,4]))
print('\n',np.linspace(1,5,num=9))

print('\n Concatenating',array_1,'with',array_2,'gives',np.concatenate((array_1,array_2)))

print('\n',array_1_row,'\non\n',2*array_1_row,'\nmakes\n',np.vstack((array_1_row,2*array_1_row)))
print('\n',array_1_row,'\nnext to\n',2*array_1_row,'\nmakes\n',np.hstack((array_1_row,2*array_1_row)))
print('\n',array_1_column,'\nnext to\n',2*array_1_column,'\nmakes\n',np.hstack((array_1_column,2*array_1_column)))

print('\n array_1.sum() =',array_1.sum())
print('\n array_1.max() =',array_1.max())
print('\n array_1.min() =',array_1.min())
print('\n array_1.mean() =',array_1.mean())


 Method 1 gives: [10 20 30 40]

 Method 2 gives: [10 20 30 40]

 A 1D row vector of the array is:
 [[10 20 30 40]]

 A 1D column vector of array is:
 [[10]
 [20]
 [30]
 [40]]

 array_1 is now [26 20 30 40]

 2*array_1 = [52 40 60 80]

 [26 20 30 40] + [1 2 3 4] = [27 22 33 44]

 [26 20 30 40] * [1 2 3 4] = [ 26  40  90 160]

 [26 20 30 40] dot [26 20 30 40] = 3576

 2D matrix:
 [[1 2 3]
 [4 5 6]]

 2D array:
 [[1 2 3]
 [4 5 6]]

 array_1 has 1 dimensions

 numpy_version has 2 dimensions

 array_1 has 4 elements

 numpy_version has 6 elements

 The shape of array_1 is (4,)

 The shape of array_1_row is (1, 4)

 The shape of array_1_column is (4, 1)

 The shape of numpy_version is (2, 3)

 array_1 is now [26 20 30 40  6]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

 Concatenating [26 20 30 40  6] with [10 20 30 40] gives [26 20 30 40  6 10 20 30 40]

 [[10 20 30 40]] 
on
 [[20 40 60 80]] 
makes
 

### Working with numpy arrays

Many Python-based numerical evaluations involve numpy arrays. To use them, you first have to import numpy. It is conventional to import it 'as np' so that you can write 'np' instead of 'numpy' when you want to use it. This is done as follows:

In [9]:
import numpy as np

Once imported, you can define a numpy array from a list. Two ways of getting to the same numpy array containing [10,20,30,40] are as follows:

In [31]:
x_list = [10,20,30,40]
array_1 = np.array(x_list)
array_2 = np.array([10,20,30,40])
print('Method 1 gives:',array_1)
print('Method 2 gives:',array_2)

Method 1 gives: [10 20 30 40]
Method 2 gives: [10 20 30 40]


It is important to note, however, that these are *neither* row *nor* column vectors as written. These are purely "one-dimensional" and are not technically 1x4 arrays but rather 0x4 arrays. This can cause problems when doing math. To specify an array as a **row vector**, add another set of brackets:

In [11]:
array_1_row = np.array([[10,20,30,40]])
print('A 1D row vector of the array is:\n', array_1_row)


 A 1D row vector of the array is:
 [[10 20 30 40]]


A **column vector** is most easily created by making the **tranpose** of a row vector using the **.T** method:

In [12]:
array_1_column = np.array([[10,20,30,40]]).T
print('A 1D column vector of array is:\n', array_1_column)


 A 1D column vector of array is:
 [[10]
 [20]
 [30]
 [40]]


Numpy elements can be changed in the same way as lists:

In [13]:
array_1[0] = 26
print('array_1 is now',array_1)


 array_1 is now [26 20 30 40]


**All elements can be mutiplied by a single value easily:**

In [14]:
print('2*array_1 =',2*array_1)


 2*array_1 = [52 40 60 80]


**Element-wise addition** can be done with a simple '+':

In [32]:
array_3 = np.array([1,2,3,4])
array_4 = array_1+array_3
print(array_1,'+',array_3,'=',array_4)

[10 20 30 40] + [1 2 3 4] = [11 22 33 44]


Element-wise subtraction is the same.

**Element-wise multiplication** can be done with a simple '*':

In [33]:
array_5 = array_1*array_3
print(array_1,'*',array_3,'=',array_5)

[10 20 30 40] * [1 2 3 4] = [ 10  40  90 160]


A **matrix dot product** uses the **np.dot** function:

In [34]:
array_6 = np.dot(array_1,array_1)
print(array_1_row,'\ndot\n',array_1_column,'=',array_6)

[[10 20 30 40]] 
dot
 [[10]
 [20]
 [30]
 [40]] = 3000


A matrix can be created either with **np.matrix()** or simply with **np.array()** but with two dimensions:

In [28]:
numpy_version = np.array(([1,2,3],[4,5,6]))
print('2D matrix:\n',matrix_version)
print('\n2D array:\n',numpy_version)

2D matrix:
 [[1 2 3]
 [4 5 6]]

2D array:
 [[1 2 3]
 [4 5 6]]


Usually an array is better to work with. The main difference is what happens with default operations, such as multiplication. With numpy arrays, multiplication is element-wide. With matrices, it is the dot product.

The **number of dimensions** in an array can be found with **.dim**:

In [23]:
print('array_1 has',array_1.ndim,'dimensions')
print('numpy_version has',numpy_version.ndim,'dimensions')

array_1 has 1 dimensions
numpy_version has 2 dimensions


The **number of elements** can be read from **.size**:

In [30]:
print('array_1 has',array_1.size,'elements')
print('numpy_version has',numpy_version.size,'elements')

array_1 has 4 elements
numpy_version has 6 elements


The size of an array can be addressed with **np.shape()**. This is where the difference between a default 1D numpy array, row vector, and column vector will differ

In [29]:
print('The shape of array_1 is',np.shape(array_1))
print('The shape of numpy_version is',np.shape(numpy_version))

The shape of array_1 is (4,)
The shape of numpy_version is (2, 3)


Note that the shape of the 1-D array is (5,) not (5,1) or (1,5). When a numpy array is made, it is **by default neither a row nor column vector**. **To turn a 1-D array into a row or column vecor**, the simplest method is to simply add an axis:

In [35]:
array_1_row = array_1[np.newaxis,:]
array_1_column = array_1[:,np.newaxis]
print('array_1_row is',array_1_row,'with shape',np.shape(array_1_row))
print('array_1_column is',array_1_column,'with shape',np.shape(array_1_column))

array_1_row is [[10 20 30 40]] with shape (1, 4)
array_1_column is [[10]
 [20]
 [30]
 [40]] with shape (4, 1)


Some **very convenient arrays** that can be generated include **arrays of all ones with np.ones(dim)**, **arrays of all zeros with np.zeros(dim)**, and **arrays with evenly spaced values with np.linspace(val1,val2,num=#elements):

In [39]:
print('\n',np.ones([3,4]))
print('\n',np.zeros([3,4]))
print('\n',np.linspace(1,5,num=9))


 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


You can also append to numpy arrays like with lists, but it is slightly different. To add another element, you need to redefine your array using np.append(). For example, a fifth element of '6' can be added to array_1 as follows:

In [40]:
array_1 = np.append(array_1,6)
print('\n array_1 is now',array_1)


 array_1 is now [10 20 30 40  6]


Multiple arrays can be combined with **np.concatenate()**:

In [41]:
print('\n Concatenating',array_1,'with',array_2,'gives',np.concatenate((array_1,array_2)))


 Concatenating [10 20 30 40  6] with [10 20 30 40] gives [10 20 30 40  6 10 20 30 40]


Notice the double parentheses; this is important. You are putting in one element consisting of two arrays, not two elements that are each arrays. **This is an easy mistake to make**.

Multiple **rows** of the **same size** can be **stacked** with **np.hstack** and the same is true with **columns** and **vstack**:

In [44]:
print(array_1_row,'\non\n',2*array_1_row,'\nmakes\n',np.vstack((array_1_row,2*array_1_row)))
print('\n',array_1_row,'\nnext to\n',2*array_1_row,'\nmakes\n',np.hstack((array_1_row,2*array_1_row)))
print('\n',array_1_column,'\nnext to\n',2*array_1_column,'\nmakes\n',np.hstack((array_1_column,2*array_1_column)))

[[10 20 30 40]] 
on
 [[20 40 60 80]] 
makes
 [[10 20 30 40]
 [20 40 60 80]]

 [[10 20 30 40]] 
next to
 [[20 40 60 80]] 
makes
 [[10 20 30 40 20 40 60 80]]

 [[10]
 [20]
 [30]
 [40]] 
next to
 [[20]
 [40]
 [60]
 [80]] 
makes
 [[10 20]
 [20 40]
 [30 60]
 [40 80]]


Some final things to cover include **simple math on arrays** and **statistics**. You can add all elements together with **.sum()**, find the max value with **.max()**, find the min value with **.max()**, find the mean with **.mean()**.

In [45]:
print('\n array_1.sum() =',array_1.sum())
print('\n array_1.max() =',array_1.max())
print('\n array_1.min() =',array_1.min())
print('\n array_1.mean() =',array_1.mean())


 array_1.sum() = 106

 array_1.max() = 40

 array_1.min() = 6

 array_1.mean() = 21.2


## Some more miscellaneous tips

Access the last element in a list with [-1]. For example:

    x_list = [1,2,3,4,99]
    print('\n The last element in',x_list,'is',x_list[-1])

Access an entire row or column with ':' instead of a specific element. For example:

    x_2D = np.array(([1,2,3],[8,1,1]))
    x_2D_row_first = x_2D[0,:]
    x_2D_column_last = x_2D[:,-1]
    print('\n x_2D is\n',x_2D) 
    print('\n The first row in x_2D is',x_2D_row_first)
    print('\n The last column in x_2D is',x_2D_column_last)

Change a numpy array to a list with .tolist():
    
    import numpy as np
    numpy_ones = np.ones(6)
    list_ones = numpy_ones.tolist()
    print('\n numpy_ones type is',type(numpy_ones))
    print('\n list_ones type is',type(list_ones))

In [197]:
x_list = [1,2,3,4,99]
print('\n The last element in',x_list,'is',x_list[-1])

x_2D = np.array(([1,2,3],[8,1,1]))
x_2D_row_first = x_2D[0,:]
x_2D_column_last = x_2D[:,-1]
print('\n x_2D is\n',x_2D) 
print('\n The first row in x_2D is',x_2D_row_first)
print('\n The last column in x_2D is',x_2D_column_last)

import numpy as np
numpy_ones = np.ones(6)
list_ones = numpy_ones.tolist()
print('\n numpy_ones type is',type(numpy_ones))
print('\n list_ones type is',type(list_ones))


 The last element in [1, 2, 3, 4, 99] is 99

 x_2D is
 [[1 2 3]
 [8 1 1]]

 The first row in x_2D is [1 2 3]

 The last column in x_2D is [3 1]

 numpy_ones type is <class 'numpy.ndarray'>

 list_ones type is <class 'list'>


## Additional information

We may use additional data structures at some point, but for now this is sufficient. You can always search for the documentation or simply 'how to do a thing' online. There are many forums such as Stack Overflow where people have asked and answered many of the questions you are likely to ask.

In [193]:
np.ones(6)

AttributeError: 'numpy.ndarray' object has no attribute 'to_list'