# Changing list and array dimensions

In [1]:
list_1 = [1,2,3,4]
print(list_1)
print(np.shape(list_1))

[1, 2, 3, 4]
(4,)


In [2]:
list_2 = [[1,2,3,4]]
print(list_2)
print(np.shape(list_2))

[[1, 2, 3, 4]]
(1, 4)


In [3]:
list_3 = [[1],[2],[3],[4]]
print(list_3)
print(np.shape(list_3))

[[1], [2], [3], [4]]
(4, 1)


In [4]:
import numpy as np
array_1 = np.array(list_1)
print(array_1)
print(np.shape(array_1))

[1 2 3 4]
(4,)


In [5]:
import numpy as np
array_1 = np.array([1,2,3,4])
print(array_1)
print(np.shape(array_1))

[1 2 3 4]
(4,)


In [6]:
import numpy as np
array_2 = np.array(list_2)
print(array_2)
print(np.shape(array_2))

[[1 2 3 4]]
(1, 4)


In [7]:
import numpy as np
array_2 = np.array([[1,2,3,4]])
print(array_2)
print(np.shape(array_2))

[[1 2 3 4]]
(1, 4)


In [8]:
import numpy as np
array_3 = np.array(list_3)
print(array_3)
print(np.shape(array_3))

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [9]:
import numpy as np
array_3 = np.array([[1],[2],[3],[4]])
print(array_3)
print(np.shape(array_3))

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [10]:
import numpy as np
array_3 = np.array(list_2).T
print(array_3)
print(np.shape(array_3))

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [14]:
print(array_1)
print(array_1.reshape(4,1))
print(array_1)
print(array_1.reshape(1,4))

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]
[[1 2 3 4]]


In [38]:
print(array_3)
print(array_3.reshape(4))
print(array_3.reshape(1,4))
print(array_3)

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [39]:
print(array_3)
array_3 = array_3.reshape(4)
print(array_3)
array_3 = array_3.reshape(4,1)
print(array_3)
array_3 = array_3.reshape(1,4)
print(array_3)
array_3 = array_3.reshape(4,1)
print(array_3)

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
