# Multiple reaction equilibrium: Gibbs energy minimization approach

## Example 1: $I+B\rightleftharpoons P$

In [1]:
######## Gibbs energy minimization approach for solving chemical equilibrium

### Import packages

import numpy as np
from scipy.optimize import minimize

### Species vector
A = ['I','B','P1','P2']

### Stoichometric matrix
nu = np.array([[-1,-1,1,0],
               [-1,-1,0,1]])

### Reaction thermodynamics
K = np.array([[108,284]]).T

### Choose reactions
rxns = [0,1] # Specify a list (e.g., [0,2] will pick the first and third)

nu=nu[rxns,:]
K = K[rxns,:]

delta = nu.sum(1)   # Calculate delta by summing along rows
n_reactions = np.shape(nu)[0]   # Number of reactions = number of rows in nu
n_species = np.shape(nu)[1]     # Number of species = number of columns in nu

### Initial conditions
y0 = np.array([[0.5,0.5,0,0]]).T
P = 2.5  #atm
Pref = 1 #atm

### Guess reaction extents
xip_g = 0.1*np.ones(len(rxns)) # Guess 0.1 for all by default. Can add another line with specifics if desired

###
def Gmin(U):
    
    xip = np.reshape(U,[len(U),1]) 
    y = 1/(1+np.dot(delta,xip))*(y0+np.dot(nu.T,xip))
    a = P/Pref*y
    
    ### First term
    G_term1 = 0 
    for i in range(n_reactions):
        G_term1 = G_term1-xip[i]*np.log(K[i,0])      

    ### Second term
    G_term2 = 0 
    for j in range(n_species):
        valj = y0[j]
        for i in range(n_reactions):
            valj = valj + nu[i,j]*xip[i]
        if a[j]>0:
            valj = valj * np.log(a[j])
        else:
            a[j]=0.000000001
            valj = valj * np.log(a[j])
        G_term2 = G_term2 + valj

    Gm = G_term1 + G_term2
    
    return Gm

def ineq1(U):
    xip = np.reshape(U,[len(U),1]) 
    y = 1/(1+np.dot(delta,xip))*(y0+np.dot(nu.T,xip))
    greaterthanzero = y.T[0].tolist()
    
    return greaterthanzero
    
### Run minimization
soln = minimize(Gmin,xip_g,method='trust-constr',constraints=dict(type='ineq',fun=ineq1))

### Report whether solver successful and solution
print('Success =',soln.success,'\n')

print('Gmin = \n',soln.fun[0],'\n')

xipsoln = np.reshape(soln.x,[len(soln.x),1]) 
print('xip = \n',xipsoln,'\n')

ysoln = 1/(1+np.dot(delta,xipsoln))*(y0+np.dot(nu.T,xipsoln))
print('y = \n',ysoln)

Success = True 

Gmin = 
 -2.559423952073772 

xip = 
 [[0.13335693]
 [0.35067906]] 

y = 
 [[0.03094016]
 [0.03094016]
 [0.25846169]
 [0.67965799]]


## Example 2: ethanol conversion

In [2]:
######## Gibbs energy minimization approach for solving chemical equilibrium

### Import packages

import numpy as np
from scipy.optimize import minimize

### Stoichiometric matrix
nu = np.array([[-1,1,1,0,0,0,0],
               [-2,0,1,1,0,0,0],
               [-1,0,0,0,1,1,0]])

### Reaction thermodynamics
dHrxn = np.array([[45.3,-24.4,68.5]]).T*1000  # J / mol rxn
dSrxn = np.array([[125.6,-35.5,98.2]]).T      # J / mol rxn
T = 473
R = 8.314
dGrxn = dHrxn-T*dSrxn
K = np.exp(-dGrxn/R/T)

### Initial conditions
y0 = np.array([[1,0,0,0,0,0,0]]).T
P = 2.5  #atm
Pref = 1 #atm

### Choose reactions
rxns = [0,1,2] # Specify a list (e.g., [0,2] will pick the first and third)

nu=nu[rxns,:]
K = K[rxns,:]

delta = nu.sum(1)   # Calculate delta by summing along rows
n_reactions = np.shape(nu)[0]   # Number of reactions = number of rows in nu
n_species = np.shape(nu)[1]     # Number of species = number of columns in nu

### Guess reaction extents
xip_g = 0.1*np.ones(len(rxns)) # Guess 0.1 for all by default. Can add another line with specifics if desired

###
def Gmin(U):
    
    xip = np.reshape(U,[len(U),1])   
    y = 1/(1+np.dot(delta,xip))*(y0+np.dot(nu.T,xip))
    a = P/Pref*y
    
    ### First term
    G_term1 = 0 
    for i in range(n_reactions):
        G_term1 = G_term1-xip[i]*np.log(K[i,0])      

    ### Second term
    G_term2 = 0 
    for j in range(n_species):
        valj = y0[j]
        for i in range(n_reactions):
            valj = valj + nu[i,j]*xip[i]
        if a[j]>0:
            valj = valj * np.log(a[j])
        else:
            a[j]=0.000000001
            valj = valj * np.log(a[j])
        G_term2 = G_term2 + valj

    Gm = G_term1 + G_term2
    
    return Gm

def ineq1(U):
    xip = np.reshape(U,[len(U),1]) 
    y = 1/(1+np.dot(delta,xip))*(y0+np.dot(nu.T,xip))
    greaterthanzero = y.T[0].tolist()
    
    return greaterthanzero
    
### Run minimization
soln = minimize(Gmin,xip_g,method='trust-constr',constraints=dict(type='ineq',fun=ineq1))

### Report whether solver successful and solution
print('Success =',soln.success,'\n')

print('Gmin = \n',soln.fun[0],'\n')

xipsoln = np.reshape(soln.x,[len(soln.x),1]) 
print('xip = \n',xipsoln,'\n')

ysoln = 1/(1+np.dot(delta,xipsoln))*(y0+np.dot(nu.T,xipsoln))
print('y = \n',ysoln)

Success = True 

Gmin = 
 -3.201982661283445 

xip = 
 [[0.94395505]
 [0.00735367]
 [0.00954869]] 

y = 
 [[0.01627277]
 [0.48321128]
 [0.48697563]
 [0.00376435]
 [0.00488798]
 [0.00488798]
 [0.        ]]
