# Stoichiometry Exercises

*These exercises accompany Lecture 2.*

In [66]:
###### Exercise 1
import numpy as np

A_NO_ox = ['NO','O2','NO2']
nu_NO_ox = np.array([[-2,-1,2]])
M_NO_ox = np.array([[30.01,32.00,46.01]]).T
print('NO oxidation nu matrix:\n',nu_NO_ox)
print('\nNO oxidation: nu dot M =',np.dot(nu_NO_ox,M_NO_ox))
print('\nEntries that are essentially zero:\n', np.dot(nu_NO_ox,M_NO_ox)**2<1E-13)

A_wgs = ['H','H2','OH','H2O','CO','CO2']
nu_wgs = np.array([[0,1,0,-1,-1,1],[-1,1,1,-1,0,0],[1,0,-1,0,-1,1]])
M_wgs = np.array([[1.01,2.02,17.01,18.02,28.01,44.01]]).T
print('\n\nWGS nu matrix:\n',nu_wgs)
print('\nWGS: nu dot M=\n',np.dot(nu_wgs,M_wgs)) 
print('\nEntries that are essentially zero:\n', np.dot(nu_wgs,M_wgs)**2<1E-13)


NO oxidation nu matrix:
 [[-2 -1  2]]

NO oxidation: nu dot M = [[-1.42108547e-14]]

Entries that are essentially zero:
 [[ True]]


WGS nu matrix:
 [[ 0  1  0 -1 -1  1]
 [-1  1  1 -1  0  0]
 [ 1  0 -1  0 -1  1]]

WGS: nu dot M=
 [[ 0.00000000e+00]
 [ 1.99840144e-15]
 [-3.55271368e-15]]

Entries that are essentially zero:
 [[ True]
 [ True]
 [ True]]


In [67]:
###### Exercise 2
from numpy.linalg import matrix_rank as rank # Not essential, but makes things easier to read

rank_NO_ox = rank(nu_NO_ox)
print('Rank of NO oxidation nu matrix =',rank_NO_ox)

n_rxns_NO_ox = np.shape(nu_NO_ox)[0] # number of rows

### If-then statements written to describe linear dependence
if rank_NO_ox < n_rxns_NO_ox:
    print('The reactions are linearly dependent.')
    print('There are',n_rxns_NO_ox-rank_NO_ox,'more reactions than needed to satisfy the overall balance.')
elif rank_NO_ox == n_rxns_NO_ox:
    print('All reactions are linearly independent.')
elif rank_NO_ox > n_rxns_NO_ox:
    print('This is not possible. Check your work.')

rank_wgs = rank(nu_wgs)
print('\nRank of WGS nu matrix =',rank_wgs)

n_rxns_wgs = np.shape(nu_wgs)[0]

### If-then statements written to describe linear dependence
if rank_wgs < n_rxns_wgs:
    print('The reactions are linearly dependent.')
    print('There are',n_rxns_wgs-rank_wgs,'more reactions than needed to satisfy the overall balance.')
elif rank_wgs == n_rxns_wgs:
    print('All reactions are linearly independent.')
elif rank_wgs > n_rxns_wgs:
    print('This is not possible. Check your work.')


Rank of NO oxidation nu matrix = 1
All reactions are linearly independent.

Rank of WGS nu matrix = 2
The reactions are linearly dependent.
There are 1 more reactions than needed to satisfy the overall balance.


In [68]:
###### Exercise 3

print('nu_NO_ox is\n',nu_NO_ox,'\nand its transpose is\n',nu_NO_ox.T)
r_NO_ox = [5]
R_NO_ox = np.dot(nu_NO_ox.T,r_NO_ox)
#print('Given that r_NO_ox is:\n',r_NO_ox,'we find that R_NO_ox is\n',R_NO_ox_labels,'=',R_NO_ox)

print('\nnu_wgs is\n',nu_wgs,'\nand its transpose is\n',nu_wgs.T)
r_wgs = np.array([[1],[2],[4]])
R_wgs = np.dot(nu_wgs.T,r_wgs)
print('Given that r_wgs is:\n',r_wgs,'\nwe find that R_wgs is\n',R_wgs)

import pandas as pd
r_wgs_df = pd.DataFrame(data=R_wgs,index=A_wgs,columns=['R_j'])
r_wgs_df


nu_NO_ox is
 [[-2 -1  2]] 
and its transpose is
 [[-2]
 [-1]
 [ 2]]

nu_wgs is
 [[ 0  1  0 -1 -1  1]
 [-1  1  1 -1  0  0]
 [ 1  0 -1  0 -1  1]] 
and its transpose is
 [[ 0 -1  1]
 [ 1  1  0]
 [ 0  1 -1]
 [-1 -1  0]
 [-1  0 -1]
 [ 1  0  1]]
Given that r_wgs is:
 [[1]
 [2]
 [4]] 
we find that R_wgs is
 [[ 2]
 [ 3]
 [-2]
 [-3]
 [-5]
 [ 5]]


R_j
H      2
H2     3
OH    -2
H2O   -3
CO    -5
CO2    5

In [69]:
### Exercise 4

nu_inv = 

(1, 3)